# 1. Configurações de Conexão com o MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/sistema_estoque?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root}

# 2. Comportamento do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true